# -*- coding: utf-8 -*-
"""virtual-assistent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qkT0SnqFbVKhBuqYhjeAXxud2IyWwj23
"""

!pip install SpeechRecognition gTTS geopy pydub
!apt-get install ffmpeg

import webbrowser
import speech_recognition as sr
from gtts import gTTS
from IPython.display import Audio, display
from pydub import AudioSegment
from google.colab import files

# Função para converter .ogg para .wav
def converter_ogg_para_wav(input_file):
    audio = AudioSegment.from_ogg(input_file)
    output_file = "audio_convertido.wav"
    audio.export(output_file, format="wav")
    return output_file

# Função para transformar texto em áudio e reproduzir
def falar_texto(texto):
    tts = gTTS(text=texto, lang='pt-br')
    tts.save("resposta.mp3")
    display(Audio("resposta.mp3", autoplay=True))

# Função para reconhecimento de áudio de arquivo (Speech-to-Text)
def reconhecer_audio_arquivo(audio_file):
    recognizer = sr.Recognizer()
    with sr.AudioFile(audio_file) as source:
        audio_data = recognizer.record(source)
        try:
            texto = recognizer.recognize_google(audio_data, language="pt-BR")
            print(f"Texto reconhecido: {texto}")
            return texto.lower()
        except sr.UnknownValueError:
            print("Não foi possível entender o áudio.")
            return ""
        except sr.RequestError:
            print("Erro ao conectar com o serviço de reconhecimento.")
            return ""

# Funções de Ações Específicas
def abrir_youtube(pesquisa):
    url = f"https://www.youtube.com/results?search_query={pesquisa}"
    webbrowser.open(url)
    resposta = f"Abrindo o YouTube para: {pesquisa}"
    print(resposta)
    falar_texto(resposta)

def abrir_wikipedia(pesquisa):
    url = f"https://pt.wikipedia.org/wiki/{pesquisa.replace(' ', '_')}"
    webbrowser.open(url)
    resposta = f"Pesquisando no Wikipedia: {pesquisa}"
    print(resposta)
    falar_texto(resposta)

def localizar_farmacia():
    url = "https://www.google.com/maps/search/farmácia+perto+de+mim"
    webbrowser.open(url)
    resposta = "Abrindo o Google Maps para localizar farmácias próximas."
    print(resposta)
    falar_texto(resposta)

def pesquisar_google(pesquisa):
    url = f"https://www.google.com/search?q={pesquisa.replace(' ', '+')}"
    webbrowser.open(url)
    resposta = f"Pesquisando no Google: {pesquisa}"
    print(resposta)
    falar_texto(resposta)

# Função para executar os comandos reconhecidos
def executar_comando(comando):
    print(f"Comando recebido: {comando}")  # Imprimir o comando recebido
    if "youtube" in comando:
        pesquisa = comando.replace("youtube", "").strip()
        abrir_youtube(pesquisa)
    elif "wikipedia" in comando:
        pesquisa = comando.replace("wikipedia", "").strip()
        abrir_wikipedia(pesquisa)
    elif "localizar farmácia" in comando:
        localizar_farmacia()
    else:
        # Se o comando não for reconhecido, pesquisar no Google
        pesquisar_google(comando)

# Função Principal para o Assistente Virtual
def assistente_virtual(audio_file):
    comando = reconhecer_audio_arquivo(audio_file)
    if comando:
        executar_comando(comando)

# Código para Upload e Execução do Assistente
uploaded = files.upload()
audio_file = next(iter(uploaded.keys()))
audio_wav = converter_ogg_para_wav(audio_file)
assistente_virtual(audio_wav)

